/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6753. Copyright MediaTek Inc. (C) 2013.
 * Wed May 27 22:13:36 2015
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_SIM1     GPIO_VIO18
#define GPIO_DVDD28_SIM2     GPIO_VIO18
#define GPIO_DVDD28_MC1     GPIO_VIO28
#define GPIO_DVDD28_MC2     GPIO_VIO18


