/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6753. Copyright MediaTek Inc. (C) 2013.
 * Thu Nov 05 22:03:51 2015
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1


#define PAD_ANT_SEL1		2
#define PAD_ANT_SEL2		1
#define PAD_CMDAT1		0
#define PAD_EINT1		0
#define PAD_EINT2		0
#define PAD_EINT3		0
#define PAD_EINT8		1
#define PAD_EINT9		2
#define PAD_EINT10		0
#define PAD_EINT11		1
#define PAD_EINT12		2
#define PAD_SCL3		1
#define PAD_SDA3		2


#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1




#define CUST_EINT_MD1_0_NAME             "MD1_SIM1_HOT_PLUG_EINT"
#define CUST_EINT_MD1_0_NUM              0
#define CUST_EINT_MD1_0_DEBOUNCE_CN      0
#define CUST_EINT_MD1_0_POLARITY         CUST_EINT_POLARITY_HIGH
#define CUST_EINT_MD1_0_SENSITIVE        CUST_EINT_MD_LEVEL_SENSITIVE
#define CUST_EINT_MD1_0_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE
#define CUST_EINT_MD1_0_DEDICATED_EN     0
#define CUST_EINT_MD1_0_SRCPIN           PAD_ANT_SEL1

#define CUST_EINT_MD1_CNT      1


