/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6753. Copyright MediaTek Inc. (C) 2013.
 * Fri Jun 12 17:34:15 2015
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1


#define PAD_ANT_SEL1		2
#define PAD_ANT_SEL2		1
#define PAD_CMDAT1		0
#define PAD_EINT1		0
#define PAD_EINT2		0
#define PAD_EINT3		0
#define PAD_EINT8		1
#define PAD_EINT9		2
#define PAD_EINT10		0
#define PAD_EINT11		1
#define PAD_EINT12		2
#define PAD_SCL3		1
#define PAD_SDA3		2


#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1




#define CUST_EINT_MD1_CNT      0


