include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/lu3010/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y	+=  leadingui_lu2x3x.o

