# Vanzo:wangfei on: Tue, 10 Mar 2015 16:03:02 +0800
# this is a example to add a hall

include $(srctree)/drivers/misc/mediatek/Makefile.custom

#below is a example
# Linux driver folder
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/hall/dummy_hall/
obj-y	+=  dummy.o

# End of Vanzo:wangfei
